# Generated by Django 5.2.4 on 2026-04-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='ai_images/'),
        ),
    ]
